Removed duplicate string to lowercase statement
The function already sends it to lowercase, so it isn't needed to repeat that. Also, it's filling the logs with "AttributeError: 'builtin_function_or_method' object has no attribute 'lower'"